logging:
  path: 'logs'
server:
  port: 43596
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: 'dev'
  resources:
    add-mappings: false
---
spring:
  profiles: 'dev'
---
spring:
  profiles: 'prod'
